name: build 

env:
  artifactName: buildArtifact

on:
  pull_request:
    branches: main

  push:
    branches: 
      - main

  workflow_dispatch:

  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Publish both API and Web App
    - name: Publish API
      run: dotnet publish ./TooGoodToGoAvans.WebApi --output ./publish/api --configuration Release

    - name: Publish Web App
      run: dotnet publish ./TooGoodToGoAvans.UI --output ./publish/webapp --configuration Release

    # Bundle EF migrations (Main Application)
    - name: Bundle EF project (Main App)
      env:
        AZURE_DB_CONNECTION: ${{ secrets.AZURE_DB_CONNECTION }}
      run:  |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef migrations bundle \
          --output ./publish/migrations/main_migrations.exe \
          --startup-project ./TooGoodToGoAvans.WebApi \
          --project ./TooGoodToGoAvans.Infrastructure \
          --self-contained -r linux-x64 \
          --context TooGoodToGoAvansDBContext \
          --connection "$AZURE_DB_CONNECTION"
    
    # Bundle EF migrations (Identity Framework)
    - name: Bundle EF project (Identity Framework)
      env:
        AZURE_AUTH_DB_CONNECTION: ${{ secrets.AZURE_AUTH_DB_CONNECTION }}
      run:  |
        dotnet tool restore
        dotnet ef migrations bundle \
          --output ./publish/migrations/identity_migrations.exe \
          --startup-project ./TooGoodToGoAvans.WebApi \
          --project ./TooGoodToGoAvans.Infrastructure \
          --self-contained -r linux-x64 \
          --context TooGoodToGoAvansDBContext_IF \
          --connection "$AZURE_AUTH_DB_CONNECTION"
    

    # Upload artifacts
    - name: Upload artifact API
      uses: actions/upload-artifact@v4
      with:
          name: deploy-api
          path: ./publish/api
          
    - name: Upload artifact WebApp
      uses: actions/upload-artifact@v4
      with:
          name: deploy-webapp
          path: ./publish/webapp

    - name: Upload artifact Migrations (Main)
      uses: actions/upload-artifact@v4
      with:
          name: deploy-migrations-main
          path: ./publish/migrations/main_migrations

    - name: Upload artifact Migrations (Identity)
      uses: actions/upload-artifact@v4
      with:
          name: deploy-migrations-identity
          path: ./publish/migrations/identity_migrations
