name: deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml  
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Download API artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy-api
        path: ./api

    - name: Download WebApp artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy-webapp
        path: ./webapp

    - name: Download Main Migrations
      uses: actions/download-artifact@v4
      with:
        name: deploy-migrations-main
        path: ./migrations

    - name: Download Identity Migrations
      uses: actions/download-artifact@v4
      with:
        name: deploy-migrations-identity
        path: ./migrations

    # Execute EF migrations (Main Database)
    - name: Execute EF migrations (Main Database)
      run: |
        chmod +x ./migrations/main_migrations.exe
        ./migrations/main_migrations.exe --connection "Server=tcp:${{ secrets.AZURE_SQL_SERVER_NAME }}.database.windows.net,1433;Database=${{ secrets.AZURE_SQL_DATABASE_NAME }};User ID=beheerder;Password=${{ secrets.AZURE_SQL_APP_USER_PASSWORD }};Trusted_Connection=False;Encrypt=True;"

    # Execute EF migrations (Identity Database)
    - name: Execute EF migrations (Identity Database)
      run: |
        chmod +x ./migrations/identity_migrations.exe
        ./migrations/identity_migrations.exe --connection "Server=tcp:${{ secrets.AZURE_SQL_SERVER_NAME_IDENTITY }}.database.windows.net,1433;Database=${{ secrets.AZURE_SQL_DATABASE_NAME_IDENTITY }};User ID=beheerder;Password=${{ secrets.AZURE_SQL_IDENTITY_USER_PASSWORD }};Trusted_Connection=False;Encrypt=True;"

    # Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy API to Azure
    - name: Deploy API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.AZURE_API_APP_SERVICE_NAME }}'
        package: ./api

    # Deploy Web App to Azure
    - name: Deploy WebApp to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.AZURE_WEBAPP_APP_SERVICE_NAME }}'
        package: ./webapp

    # Set up environment variables for Main and Identity Databases
    - name: Set environment variables
      uses: azure/appservice-settings@v1
      with:
        app-name: '${{ secrets.AZURE_WEBAPP_APP_SERVICE_NAME }}'
        app-settings-json: |
          [
            {
              "name": "AzureConnection",
              "value": "Server=tcp:${{ secrets.AZURE_SQL_SERVER_NAME }}.database.windows.net,1433;Database=${{ secrets.AZURE_SQL_DATABASE_NAME }};User ID=app_user;Password=${{ secrets.AZURE_SQL_APP_USER_PASSWORD }};Trusted_Connection=False;Encrypt=True;"
            },
            {
              "name": "AzureAuthConnection",
              "value": "Server=tcp:${{ secrets.AZURE_SQL_SERVER_NAME_IDENTITY }}.database.windows.net,1433;Database=${{ secrets.AZURE_SQL_DATABASE_NAME_IDENTITY }};User ID=identity_user;Password=${{ secrets.AZURE_SQL_IDENTITY_USER_PASSWORD }};Trusted_Connection=False;Encrypt=True;"
            }
          ]
